### ISSUE TITLE
gslc_ElemXRingGaugeSetAngleRange incorrect initialization

### ISSUE THREAD

**Issue by markus-i** [ImpulseAdventure/GUIslice-Builder-source#26]
Generated code for RingGauge initialization contains:
gslc_ElemXRingGaugeSetAngleRange(&m_gui,pElemRef, 270, 360, RING-102);
According to API doc, that last attribute should be a boolean (TRUE by default?), RING isn't recognized by my Arduino IDE.
Replacing RING-102 with true at least compiles.

**Comment by Pconti31** [comment]
Fixed in 0.13.0.3
Template changed from
gslc_ElemXRingGaugeSetAngleRange(&m_gui,pElemRef, $<RING-100>, $<RING-101>, RING-102);
to
gslc_ElemXRingGaugeSetAngleRange(&m_gui,pElemRef, $<RING-100>, $<RING-101>, $<RING-102>);
Paul--

**Comment by Pconti31** [comment]
Closed because 0.13.0.3 hot fix has been posted to the GUIslice Releases.
