### ISSUE TITLE
Degree symbol not shown on display

### ISSUE THREAD

**Issue by markus-i** [ImpulseAdventure/GUIslice-Builder-source#27]
Ok, I admit - that one is nasty. Especially since my attempts to get it to show on a different display led me into the depths of controller specific character sets :-(

![Builder](https://user-images.githubusercontent.com/44025590/64350119-6ed80280-cff8-11e9-8db6-74e38df58139.jpg)

![Display](https://user-images.githubusercontent.com/44025590/64351158-1e61a480-cffa-11e9-8473-b67b84b92f8c.jpg)

**Comment by markus-i** [comment]
My bad. Just read the description of the Adafruit font library: 

> and “7b” to indicate that these contain 7-bit characters (ASCII codes “ ” through “~”); 8-bit fonts (supporting symbols and/or international characters) are not yet provided but may come later.

So this can't work, I'll have to think of something else.

**Comment by ImpulseAdventure** [comment]
Hi Markus --

Although the "7b" fonts in the Adafruit-GFX library don't natively support the degree symbol, I was able to edit the **FreeSans12pt7b** font file for you to add a degree symbol.

To use this, you can enter in the backtick symbol wherever you want to see a degree symbol, eg:
```
23.5`C
```

Example from my display:
![IMG_5792-s](https://user-images.githubusercontent.com/8510097/64402344-6d72fe00-d029-11e9-9a41-1de48c638714.jpg)

Please see the attached font file "FreeSans12pt7b_mod.h"
[FreeSans12pt7b_mod.zip](https://github.com/ImpulseAdventure/GUIslice-Builder-source/files/3582278/FreeSans12pt7b_mod.zip)

Hope that helps!

**Comment by tutoduino** [comment]
[This online tool](https://tchapi.github.io/Adafruit-GFX-Font-Customiser/) is perfect to change '`' symbol to '°' in any font
I used it in my reTerminal E1002 tutorial to display degree symbol with temperatures -> https://tutoduino.fr/en/reterminal-e1002-arduino-ide/
![°C displayed on reTerminal E1002](https://tutoduino.fr/ookoorsa/2025/10/reTerminal-Arduino-EN-1080x540.jpg)
